user_user:
    resource: "@UserUserBundle/Resources/config/routing.yml"
    prefix:   /user

home_home:
    resource: "@HomeHomeBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
